version: '{build}'

skip_tags: false
image: Visual Studio 2015
platform: Any CPU
configuration: Release

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

build_script:
  - ps: .\build.ps1

test: off

artifacts:
  - path: reports
    name: Reports
  - path: '*.nupkg'
    name: Packages

after_deploy:
  - ps: |
    & git config --global credential.helper store
    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    & git config --global user.email "Appveyor Deploy"
    & git config --global user.name "Appveyor Deploy"
    make\make.ps1 -t update-wiki

environment:
  access_token:
    secure: Xu3+xPTTII2UDM8Bc6DH0H82IlTLOdJ3+ROJBOP84PvWvuYotiNk/OHRw+eMVuur